spring.threads.virtual.enabled = true

spring.security.user.name=admin
spring.security.user.password=admin
spring.security.user.roles=ADMIN

spring.security.scoped.mode=security-filter
#tomcat-thread-executor
#none

#spring.task.execution.propagate-context=true
spring.task.execution.pool.core-size=8
spring.task.execution.pool.max-size=8
spring.task.execution.pool.queue-capacity=200
spring.task.execution.pool.keep-alive=60s

spring.task.execution.simple.concurrency-limit=1000

spring.task.execution.shutdown.await-termination=true

spring.task.execution.thread-name-prefix=application-

# spring.task.scheduling.pool.core-size=8

